title: Yuanbo Li's Homepage
page-top-title: Yuanbo Li's Homepage
top-section-bg-text: Sensing, Measuring & Robot Technology (SMART Lab)
                     Computer Science
home-subtitle: Yuanbo Li
copyright-text: '&copy; Yuanbo Li 2023-2026. All Rights Reserved.'
