title: Yuanbo Li's Homepage
page-top-title: Yuanbo Li
top-section-bg-text: Be what you wanna be
home-subtitle: Yuanbo Li&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Yuanbo Li 2023-2025. All Rights Reserved.'
